import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import './globals.css';
import { ReactNode, memo } from 'react';
import { cn } from '@/lib/utils';
import { FilterForm } from '@/components/FilterForm';
import { Genres } from './genres';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={cn('dark', GeistSans.className)}>
        <main className='h-[100dvh] w-full p-4'>{children}</main>
      </body>
    </html>
  );
}
